apis:
  device-registry:
    name: Device Registry
    prefix: device-registry
    upstream_url: http://device-registry
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 3

  dmx:
    name: DMX Controller
    prefix: dmx
    upstream_url: http://dmx
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 3
